<div id="contant_area">

  <?php



$df='main_cat_id';



$urlids=get_sub_cat($sub_cat_id);

function get_lan_lat($postcode=''){
    
    $postcode = str_replace(" ","+",$postcode);
    
    $url ="http://maps.googleapis.com/maps/api/geocode/xml?address=".$postcode."+UK&sensor=false";
    $result = simplexml_load_file($url);

    if(!empty($result->result->geometry->location)){ 
        $lat = get_object_vars($result->result->geometry->location); 
        
    } else {
        $lat = array(0,0);
    }
    
    return $lat;
    
    
} // end of function 







$tbl_name="postcode_location";







$adjacents = 3;







$sql_search_view1 = "SELECT *
FROM postcode_location
INNER JOIN ad_title_description ON ad_title_description.postcode_loaction_id = postcode_location.id WHERE  postcode_location.status ='1'
AND postcode_location.$df IN (".$urlids.") order by postcode_location.date desc";









$total_pages = mysql_query($sql_search_view1);



$total_num_rows=mysql_num_rows($total_pages);



 $total_pages = $total_num_rows;







/* Setup vars for query. */



$targetpage = $page_name;     //your file name  (the name of this file)



$limit = 10;                                 //how many items to show per page



$page = $_GET['page'];



	if($page) 



		$start = ($page - 1) * $limit; 			//first item to display on this page



	else



		$start = 0;	                              //if no page var is given, set start to 0







/* Get data. */















 $sql_search_view = "SELECT * FROM postcode_location INNER JOIN ad_title_description ON ad_title_description.postcode_loaction_id = postcode_location.id WHERE postcode_location.status ='1' AND postcode_location.$df IN (".$urlids.") order by postcode_location.date desc LIMIT $start, $limit";	







$result_search_view = mysql_query($sql_search_view);
$mappins = mysql_query($sql_search_view);



	$mrk_cnt = 0;
while ($obj =mysql_fetch_array($mappins))  // get all rows (markers)
{
    $lat[$mrk_cnt] = $obj['lat'];  // save the lattitude
    $lng[$mrk_cnt] = $obj['lang'];  // save the longitude
    $inf[$mrk_cnt] = $obj['title'];  // save the info-window
    $mrk_cnt++;                      // increment the marker counter
}
//$res->close();
// Now we have the lattitude, longitude and info-window text for each marker 
// stored in php arrays. Now we need to write the marker's JavaScript 
// dynamically with this information
	
?>

<script type='text/javascript'>
var point;
var mrktx;
function load() {
   addTo = 0;
   var latlng = new google.maps.LatLng(52.355518, -1.17432);
   var myOptions = {
      zoom: 7,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
   };
   // NOTE: all values: latitude, longitude, zoom, etc.
   //       should also come from the database for flexibility
       
   var map = new google.maps.Map(document.getElementById("map_canvas"), 
              myOptions);
// This next block of JavaScript needs to be generated by PHP 
// to 'add-in' the information from the arrays

<?php
for ($lcnt = 0; $lcnt < $mrk_cnt; $lcnt++)
{
		
    echo "var point$lcnt = new google.maps.LatLng($lat[$lcnt], $lng[$lcnt]);\n";
    echo "var mrktx$lcnt = \"$inf[$lcnt]\";\n";
	echo "var infowindow$lcnt = new google.maps.InfoWindow({
   			content: mrktx$lcnt
			});";
    echo "var marker$lcnt = new google.maps.Marker({position: point$lcnt, map: map});\n";
	echo "google.maps.event.addListener(marker$lcnt, 
         'click', function() {
   		     infowindow$lcnt.open(map,marker$lcnt);
          });\n";
}
?>
}
</script>
<?php



	$num_rows_views=mysql_num_rows($result_search_view);



	/* Setup page vars for display. */



	if ($page == 0) $page = 1;					//if no page var is given, default to 1.



	$prev = $page - 1;							//previous page is page - 1



	$next = $page + 1;							//next page is page + 1



	$lastpage = ceil($total_pages/$limit);		//lastpage is = total pages / items per page, rounded up.



	$lpm1 = $lastpage - 1;						//last page minus 1



	



	/* 



		Now we apply our rules and draw the pagination object. 



		We're actually saving the code to a variable in case we want to draw it more than once.



	*/



	$pagination = "";



	if($lastpage > 1)



	{	



		$pagination .= "<div class=\"pagination\">";



		//previous button



		if ($page > 1) 



			$pagination.= "<a href=\"$targetpage?page=$prev&sub_cat_id=$sub_cat_id\">previous</a>";



		else



			$pagination.= "<span class=\"disabled\">previous</span>";	



		



		//pages	



		if ($lastpage < 7 + ($adjacents * 2))	//not enough pages to bother breaking it up



		{	



			for ($counter = 1; $counter <= $lastpage; $counter++)



			{



				if ($counter == $page)



					$pagination.= "<span class=\"current\">$counter</span>";



				else



					$pagination.= "<a href=\"$targetpage?page=$counter&sub_cat_id=$sub_cat_id\">$counter</a>";					



			}



		}



		elseif($lastpage > 5 + ($adjacents * 2))	//enough pages to hide some



		{



			//close to beginning; only hide later pages



			if($page < 1 + ($adjacents * 2))		



			{



				for ($counter = 1; $counter < 4 + ($adjacents * 2); $counter++)



				{



					if ($counter == $page)



						$pagination.= "<span class=\"current\">$counter</span>";



					else



						$pagination.= "<a href=\"$targetpage?page=$counter&sub_cat_id=$sub_cat_id\">$counter</a>";					



				}



				$pagination.= "...";



				$pagination.= "<a href=\"$targetpage?page=$lpm1&sub_cat_id=$sub_cat_id\">$lpm1</a>";



				$pagination.= "<a href=\"$targetpage?page=$lastpage&sub_cat_id=$sub_cat_id\">$lastpage</a>";		



			}



			//in middle; hide some front and some back



			elseif($lastpage - ($adjacents * 2) > $page && $page > ($adjacents * 2))



			{



				$pagination.= "<a href=\"$targetpage?page=1&sub_cat_id=$sub_cat_id\">1</a>";



				$pagination.= "<a href=\"$targetpage?page=2&sub_cat_id=$sub_cat_id\">2</a>";



				$pagination.= "...";



				for ($counter = $page - $adjacents; $counter <= $page + $adjacents; $counter++)



				{



					if ($counter == $page)



						$pagination.= "<span class=\"current\">$counter</span>";



					else



						$pagination.= "<a href=\"$targetpage?page=$counter&sub_cat_id=$sub_cat_id\">$counter</a>";					



				}



				$pagination.= "...";



				$pagination.= "<a href=\"$targetpage?page=$lpm1&sub_cat_id=$sub_cat_id\">$lpm1</a>";



				$pagination.= "<a href=\"$targetpage?page=$lastpage&sub_cat_id=$sub_cat_id\">$lastpage</a>";		



			}



			//close to end; only hide early pages



			else



			{



				$pagination.= "<a href=\"$targetpage?page=1&sub_cat_id=$sub_cat_id\">1</a>";



				$pagination.= "<a href=\"$targetpage?page=2&sub_cat_id=$sub_cat_id\">2</a>";



				$pagination.= "...";



				for ($counter = $lastpage - (2 + ($adjacents * 2)); $counter <= $lastpage; $counter++)



				{



					if ($counter == $page)



						$pagination.= "<span class=\"current\">$counter</span>";



					else



						$pagination.= "<a href=\"$targetpage?page=$counter&sub_cat_id=$sub_cat_id\">$counter</a>";					



				}



			}



		}



		



		//next button



		if ($page < $counter - 1) 



			$pagination.= "<a href=\"$targetpage?page=$next&sub_cat_id=$sub_cat_id\">next</a>";



		else



			$pagination.= "<span class=\"disabled\">next</span>";



		$pagination.= "</div>\n";		



	}



	



	if($num_rows_views >0){



		while($row_search_view = mysql_fetch_array($result_search_view))



		{



			$user_id=$row_search_view['user_id'];



			 $post_id=$row_search_view['postcode_loaction_id'];



			



			$published_date=$row_search_view['date'];



			$town=$row_search_view['town'];



			



			



			$daysago = (strtotime($cdate) - strtotime($published_date)) / (60 * 60 * 24);



			



			 $select_image_query="SELECT postcode_loaction_id,file_name FROM users_images WHERE postcode_loaction_id='".$post_id."'  ";



			$run_image_query=mysql_query($select_image_query);



			



			$fetch_image_query=mysql_fetch_array($run_image_query);



			 $image_name=$fetch_image_query['file_name'];



			//End Image//



			



			



			$title=$row_search_view['title'];

			$url=$row_search_view['url'];



			$description=$row_search_view['description'];



			



			//End Title Description//



			



			$feature_name=$row_search_view['name'];



				$feature_price=$row_search_view['item_price'];



				$ad_price_days=$row_search_view['days'];



				



				



				$email="SELECT email,phone FROM registration WHERE id='".$user_id."'";



				$run_email=mysql_query($email);



				$fetch_email=mysql_fetch_array($run_email);



				$email_id=$fetch_email['email'];



				$phone=$fetch_email['phone'];



?>





  <section class="listing-box">

    <div class="list-image"><?php if(!empty($image_name)) { ?><a href="http://elaxy.co.uk/ad/<?=$url?>"><img src="/uploads/<?php echo $image_name; ?>" width="121" height="84" alt="" /></a> <?php } else { ?> <img src="/images/noimage_thumbnail.png" width="121" height="84" alt="" />  <?php } ?></div>

    <div class="list-detail">
	
      <div class="list-hd"><a href="http://elaxy.co.uk/ad/<?=$url?>"><?php echo $title; ?></a></div>

      <div class="list-cnt"><?php echo substr($description, 0, 70)."....."; ?></div>

      <div class="list-loc"><?php echo $town; ?></div>

    </div>

    <?php if($feature_name!="Free Ad"){ ?>

    <div class="list-feature" style="display:none;"> <?php echo $feature_name;   ?></div>

    <?php } ?>

    <div class="list-star"></div>

    <div class="list-pricing">

	 <?php if($sub_cat_id == 4) { ?>

                   

                    <?php } else if ($sub_cat_id == 5){ ?>

                    <?php } else if ($sub_cat_id == 71){ ?>
                    <?php } else if ($sub_cat_id == 72){ ?>
                    <?php } else if ($sub_cat_id == 73){ ?>
                    <?php } else if ($sub_cat_id == 74){ ?>
                    <?php } else if ($sub_cat_id == 75){ ?>
                    <?php } else if ($sub_cat_id == 78){ ?>
                    <?php } else if ($sub_cat_id == 79){ ?>
                    <?php } else if ($sub_cat_id == 80){ ?>
                    <?php } else if ($sub_cat_id == 81){ ?>
                    <?php } else if ($sub_cat_id == 82){ ?>
                    <?php } else if ($sub_cat_id == 83){ ?>

                    <?php } else if ($sub_cat_id == 8){ ?>

                     <?php } else if ($sub_cat_id == 84){ ?>

                    

                    <?php } else if ($sub_cat_id == 85){ ?>

                    <?php } else { ?>

                   <?php echo "&pound;".$feature_price."<br/> "; ?>

                    <?php } ?>

	

    

    

     <span><?php echo $daysago." "."days ago"; ?></span></div>

    <span>

    <?php //echo $phone; ?>

    </span> </section>

  <?php }  ?>
<div class="clear"></div>





       
       <div style="display:none">
    <div id="myDivID">
        <div id="map_canvas" style="width: 625px; height: 500px; margin-left:10px;"></div>
    </div>
</div>

<script type="text/javascript">
    $("a#fancyBoxLink").fancybox({
        'href'   : '#myDivID',
        'titleShow'  : false,
        'transitionIn'  : 'elastic',
        'transitionOut' : 'elastic'
    });
	
	
		
		
	
</script>


<?php  }  else{ ?>

  <?php echo "<div style='clear:both; margin-left:15px;'>Sorry no result found<div>"; } ?> <br />

  <br />

  <div style="margin-top:80px; margin-left:210px;"><?php echo $pagination; ?></div>

  <div id="demo3"> </div>

</div>