<div id="contant_area">



  <?php







$df='main_cat_id';







$urlids=get_sub_cat($sub_cat_id);



function get_lan_lat($postcode=''){

    

    $postcode = str_replace(" ","+",$postcode);

    

    $url ="http://maps.googleapis.com/maps/api/geocode/xml?address=".$postcode."+UK&sensor=false";

    $result = simplexml_load_file($url);



    if(!empty($result->result->geometry->location)){ 

        $lat = get_object_vars($result->result->geometry->location); 

        

    } else {

        $lat = array(0,0);

    }

    

    return $lat;

    

    

} // end of function 





function get_top($id){

	do{

	$query=mysql_query("select * from categories where id={$id}");

$rs=mysql_fetch_array($query);

$arr[] = $rs['id'] .'|'. $rs['name'] . '|' . $rs['cat_url'];

$id=$rs['parent_off'];



}while($rs!=0);



 krsort($arr);

// end($arr);

 

  foreach($arr as $key=>$list){



            $ex = explode("|",$list);

$ex[0]."<br>";



if($ex[0]==8){

	return true;



  }

 if($ex[0]==9){

	return true;



  }

  if($ex[0]==4){

	return true;



  }

  

  if($ex[0]==5){

	return true;



  }

  

 

	}

	}









$tbl_name="postcode_location";















$adjacents = 3;















$sql_search_view1 = "SELECT *

FROM postcode_location

INNER JOIN ad_title_description ON ad_title_description.postcode_loaction_id = postcode_location.id WHERE  postcode_location.status ='1'

AND postcode_location.$df IN (".$urlids.") order by postcode_location.date desc";



$total_pages = mysql_query($sql_search_view1);

$total_num_rows=mysql_num_rows($total_pages);

 $total_pages = $total_num_rows;

 $page = !empty($_GET['page']) ? $_GET['page'] : 1; // Setting a default value to the page

	

	$per_page = 10; // message to show per page

 

 $pagination = new Pagination($page, $per_page, $total_num_rows); // create an object of clas agination	

	// end of pagination default variables 

	

	

	$sql_search_view="SELECT * FROM postcode_location INNER JOIN ad_title_description ON ad_title_description.postcode_loaction_id = postcode_location.id WHERE postcode_location.status ='1' AND postcode_location.$df IN (".$urlids.") order by postcode_location.date desc LIMIT {$per_page} OFFSET {$pagination->offset()}";

	

 $result_search_view = mysql_query($sql_search_view);

 $mappins = mysql_query($sql_search_view);

 

 









	$mrk_cnt = 0;

while ($obj =mysql_fetch_array($mappins))  // get all rows (markers)

{

    $lat[$mrk_cnt] = $obj['lat'];  // save the lattitude

    $lng[$mrk_cnt] = $obj['lang'];  // save the longitude

    $inf[$mrk_cnt] = $obj['title'];  // save the info-window

    $mrk_cnt++;                      // increment the marker counter

}

//$res->close();

// Now we have the lattitude, longitude and info-window text for each marker 

// stored in php arrays. Now we need to write the marker's JavaScript 

// dynamically with this information

	

?>



<script type='text/javascript'>

var point;

var mrktx;

function load() {

   addTo = 0;

   var latlng = new google.maps.LatLng(52.355518, -1.17432);

   var myOptions = {

      zoom: 7,

      center: latlng,

      mapTypeId: google.maps.MapTypeId.ROADMAP

   };

   // NOTE: all values: latitude, longitude, zoom, etc.

   //       should also come from the database for flexibility

       

   var map = new google.maps.Map(document.getElementById("map_canvas"), 

              myOptions);

// This next block of JavaScript needs to be generated by PHP 

// to 'add-in' the information from the arrays



<?php

for ($lcnt = 0; $lcnt < $mrk_cnt; $lcnt++)

{

		

    echo "var point$lcnt = new google.maps.LatLng($lat[$lcnt], $lng[$lcnt]);\n";

    echo "var mrktx$lcnt = \"$inf[$lcnt]\";\n";

	echo "var infowindow$lcnt = new google.maps.InfoWindow({

   			content: mrktx$lcnt

			});";

    echo "var marker$lcnt = new google.maps.Marker({position: point$lcnt, map: map});\n";

	echo "google.maps.event.addListener(marker$lcnt, 

         'click', function() {

   		     infowindow$lcnt.open(map,marker$lcnt);

          });\n";

}

?>

}

</script>

<?php

	$num_rows_views=mysql_num_rows($result_search_view);

	/* Setup page vars for display. */

	





	







	if($num_rows_views >0){







		while($row_search_view = mysql_fetch_array($result_search_view))







		{







			$user_id=$row_search_view['user_id'];







			 $post_id=$row_search_view['postcode_loaction_id'];







			







			$published_date=$row_search_view['date'];







			$town=$row_search_view['town'];







			







			







			$daysago = (strtotime($cdate) - strtotime($published_date)) / (60 * 60 * 24);







			







			 $select_image_query="SELECT postcode_loaction_id,file_name FROM users_images WHERE postcode_loaction_id='".$post_id."'  ";







			$run_image_query=mysql_query($select_image_query);







			







			$fetch_image_query=mysql_fetch_array($run_image_query);







			 $image_name=$fetch_image_query['file_name'];







			//End Image//







			







			







			$title=$row_search_view['title'];



			$url=$row_search_view['url'];







			$description=$row_search_view['description'];







			







			//End Title Description//







			







			$feature_name=$row_search_view['name'];







				$feature_price=$row_search_view['item_price'];







				$ad_price_days=$row_search_view['days'];







				







				







				$email="SELECT email,phone FROM registration WHERE id='".$user_id."'";







				$run_email=mysql_query($email);







				$fetch_email=mysql_fetch_array($run_email);







				$email_id=$fetch_email['email'];







				$phone=$fetch_email['phone'];







?>











  <section class="listing-box">



    <div class="list-image"><?php if(!empty($image_name)) { ?><a href="http://elaxy.co.uk/ad/<?=$url?>"><img src="/uploads/<?php echo $image_name; ?>" width="121" height="84" alt="" /></a> <?php } else { ?> <img src="/images/noimage_thumbnail.png" width="121" height="84" alt="" />  <?php } ?></div>



    <div class="list-detail">

	

      <div class="list-hd"><a href="http://elaxy.co.uk/ad/<?=$url?>"><?php echo substr($title, 0, 25) ."....."; ?></a></div>



      <div class="list-cnt"><?php echo substr($description, 0, 70)."....."; ?></div>



      <div class="list-loc"><?php echo $town; ?></div>



    </div>



    <?php if($feature_name!="Free Ad"){ ?>



    <div class="list-feature" style="display:none;"> <?php echo $feature_name;   ?></div>



    <?php } ?>



    <div class="list-star"></div>



    <div class="list-pricing">



	



                    <?php $found=get_top($sub_cat_id); if($found==true){  } else { ?>



                   <?php echo "&pound;".$feature_price."<br/> "; ?>



                    <?php } ?>



	



    



    



     <span><?php echo $daysago." "."days ago"; ?></span></div>



    <span>



    <?php //echo $phone; ?>



    </span> </section>



  <?php }  ?>

<div class="clear"></div>











       

       <div style="display:none">

    <div id="myDivID">

        <div id="map_canvas" style="width: 625px; height: 500px; margin-left:10px;"></div>

    </div>

</div>



<script type="text/javascript">

    $("a#fancyBoxLink").fancybox({

        'href'   : '#myDivID',

        'titleShow'  : false,

        'transitionIn'  : 'elastic',

        'transitionOut' : 'elastic'

    });

	

	

		

		

	

</script>





<?php  }  else{ ?>



  <?php echo "<div style='clear:both; margin-left:15px;'>Sorry no result found<div>"; } ?> <br />



  <br />



  <div style="margin-top:80px; margin-left:210px;"><?php

  $targetpage =  "http://elaxy.co.uk/cat/".$_GET['caturl']."/page"; ?>

   <div class="pagination">

   <?php

   if($pagination->total_pages() > 1) { // start of pageination code ?>

  

<?php

			if($page != 1){

			if($pagination->has_previous_page()) { 

				

				

					echo "<li><a href=\"$targetpage/";

					echo $pagination->previous_page();

				echo "\">&laquo; Previous</a></li> "; 

				}

				

			}// End of if sttarment

			

			}

			for($i=1; $i <= $pagination->total_pages(); $i++) { // for looop to count number of"." pages to be displayed

					if($i == $page) {

						

						echo "<li class='active'><a href='#'> {$i} </a> </li> ";

						

					} else {																								

						echo "<li> <a href=\"$targetpage/{$i}\"> {$i} </a> </li>";

						} 

					

			}// End of for loop

			if($pagination->has_next_page()) { 

					echo "<li> <a href=\"$targetpage/";



					echo $pagination->next_page();

					echo "\">Next &raquo;</a></li> "; 

					

					

					

			}// end of if steatemetn

		echo "</div>";

		

		// End of pagination code	 ?></div>



  <div id="demo3"> </div>



</div>